FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -q dependency:go-offline
COPY src ./src
RUN mvn -q clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
RUN addgroup -S gymflow && adduser -S gymflow -G gymflow
COPY --from=build /app/target/gymflow-pro.jar app.jar
USER gymflow
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
